name: Qure图标-sync
on:
  schedule:
    - cron: '4 */2 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Koolson-Qure
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Koolson-Qure
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Koolson/Qure.git"
          source_branch: "master"
          destination_branch: "Qure图标"
          github_token: ${{ secrets.PAT }}
